# Exported from Render on 2025-09-03T19:32:12Z
services:
  - type: web
    name: AbletonLive-API-Stub
    runtime: python
    repo: https://github.com/isfopo/LiveAPI_MakeDoc
    branch: flask-server-for-mcp
    plan: free
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    autoDeployTrigger: commit
    rootDir: server
version: "1"
