name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Latest Version
        id: get_version
        run: |
          latest_version=$(ls build | sort -V | tail -n 1)
          echo "version=$latest_version" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install
        working-directory: .github/scripts

      - name: Zip Build Folder
        run: |
          cd build/${{ steps.get_version.outputs.version }}
          zip -r ../../${{ steps.get_version.outputs.version }}.zip .

      - name: Delete existing release (if any)
        run: node .github/scripts/delete_release.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.version }}
          GITHUB_REPO: ${{ github.repository }}

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create GitHub Release
        run: |
          gh release create "v${{ steps.get_version.outputs.version }}" "${{ steps.get_version.outputs.version }}.zip" --title "v${{ steps.get_version.outputs.version }}" --notes "Release version v${{ steps.get_version.outputs.version }}"

      # - name: Upload Release Asset
      #   run: |
      #     gh release upload "v${{ steps.get_version.outputs.version }}" "${{ steps.get_version.outputs.version }}.zip" --clobber
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
