name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Latest Version
        id: get_version
        run: |
          latest_version=$(ls build | sort -V | tail -n 1)
          echo "version=$latest_version" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Zip Build Folder
        run: |
          cd build/${{ steps.get_version.outputs.version }}
          zip -r ../../${{ steps.get_version.outputs.version }}.zip .

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/${{ steps.get_version.outputs.version }}/
          asset_name: ${{ steps.get_version.outputs.version }}.zip
          asset_content_type: application/zip
