name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Latest Version
        id: get_version
        run: |
          latest_version=$(ls build | sort -V | tail -n 1)
          echo "version=$latest_version" >> $GITHUB_OUTPUT

      - name: Determine Previous Version
        id: get_previous_version
        run: |
          previous_version=$(ls build | sort -V | tail -n 2 | head -n 1)
          echo "previous_version=$previous_version" >> $GITHUB_OUTPUT

      - name: Compute Live.xml Changes
        id: compute_diff
        run: |
          if [ -z "${{ steps.get_previous_version.outputs.previous_version }}" ]; then
            echo "No previous version found. Using entire Live.xml as release notes."
            diff_content=$(cat build/${{ steps.get_version.outputs.version }}/Live.xml)
          else
            diff_content=$(diff build/${{ steps.get_previous_version.outputs.previous_version }}/Live.xml build/${{ steps.get_version.outputs.version }}/Live.xml || true)
            if [ -z "$diff_content" ]; then
              diff_content="No changes in Live.xml since the previous release."
            fi
          fi
          echo "$diff_content" > release_notes.txt

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install
        working-directory: .github/scripts

      - name: Zip Build Folder
        run: |
          cd build/${{ steps.get_version.outputs.version }}
          zip -r ../../${{ steps.get_version.outputs.version }}.zip .

      - name: Delete existing release (if any)
        run: node .github/scripts/delete_release.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.version }}
          GITHUB_REPO: ${{ github.repository }}

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create GitHub Release
        run: |
          gh release create "${{ steps.get_version.outputs.version }}" "${{ steps.get_version.outputs.version }}.zip" --title "Ableton Live Version: ${{ steps.get_version.outputs.version }}" --notes-file release_notes.txt
